# Generated by Django 5.0.6 on 2024-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pots",
            new_name="Post",
        ),
    ]
